name: 'Go build and test'
description: 'Build and test a Go project'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      shell: bash
      run: go build -v ./...

    - name: Test
      shell: bash
      run: go test -v ./...